---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  gms-logging-psp-role
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
    - use
