#!/bin/bash

#
# This script installs the prerequisites required to build the GMS PI 17 open
# source release.  It's intended to be run on a CentOS/RHEL 7 system.
#

set -eux

if [ -z "${1:-}" ]; then
    TARGET_USER=${USER}
else
    TARGET_USER=${1}
fi

# enable ip_forward for docker
if [[ "$(sudo sysctl net.ipv4.ip_forward)" != "net.ipv4.ip_forward = 1" ]]; then
  echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p
  sudo systemctl restart network
fi

# Base tools
sudo yum install -y git unzip vim yum-utils

# Docker CE
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod --groups docker --append ${TARGET_USER}

# Java
sudo yum install -y java-11-openjdk-devel
JAVA11_DIR=$(ls -d /usr/lib/jvm/java-11-openjdk-11*.x86_64)
sudo alternatives --set java ${JAVA11_DIR}/bin/java
java --version

# Gradle
GRADLE_VERSION=6.6.1
curl https://downloads.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle-${GRADLE_VERSION}-bin.zip
sudo unzip -d /opt /tmp/gradle-${GRADLE_VERSION}-bin.zip
sudo mv /opt/gradle-${GRADLE_VERSION} /opt/gradle
echo 'export PATH=$PATH:/opt/gradle/bin' | sudo tee /etc/profile.d/gradle.sh

# NodeJS and Yarn
curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
curl -fsSL https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum groupinstall -y "Development Tools"
sudo yum install -y yarn nodejs-10.19.0 postgresql-devel
sudo yarn config set disable-self-update-check true

echo "Prerequisites installed! Be sure to logout and login to ensure environment is updated."
