NAME = reactive-interaction-gateway

BUILD_ARGS = --build-arg 'FROM_IMAGE=$${CI_THIRD_PARTY_DOCKER_REGISTRY}/accenture/reactive-interaction-gateway:3.0.0-alpha.1'

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.docker
