{{- $appName := "etcd" }}
{{- $appValues := get .Values $appName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    restartAfterReconfig: {{ include "soh.deployment.restartAfterReconfig" (dict "Values" .Values "appValues" $appValues) }}
spec:
  replicas: {{ $appValues.replicas }}
  strategy:
    type: {{ include "soh.deployment.strategy" (dict "Values" .Values "appValues" $appValues) }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: gms-soh-elevated
      containers:
        - name: {{ $appName }}
          image: {{ include "soh.container.image" (dict "Values" .Values "appValues" $appValues) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: GMS_ETCD_USER
              valueFrom:
                secretKeyRef:
                  name: "etcd-gms-user"
                  key:  username
            - name: GMS_ETCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "etcd-gms-user"
                  key: password
            - name: GMS_ETCD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: "etcd-admin-user"
                  key:  username
            - name: GMS_ETCD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "etcd-admin-user"
                  key: password
            - name: GMS_ETCD_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: "etcd-root-user"
                  key:  username
            - name: GMS_ETCD_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "etcd-root-user"
                  key: password
            {{- include "soh.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) }}
          ports:
            - containerPort: 2379
          {{- include "soh.container.resources" (dict "Values" .Values "appValues" $appValues) | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  type: ClusterIP
  ports:
    - name: grpc-etcd
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: {{ $appName }}
