# ----------------------------------------------------------------------------
# [ TEST ] SOH Alive
#
# description:
#   This test augmentation runs SOH-specific alive endpoint test
# ----------------------------------------------------------------------------
---
kind: Augmentation
metadata:
  type: test
  values:
    appName: test-soh-alive
    imageName: gms-common/alive-tests
  labels:
    - test
    - soh
    - checkout
  wait:
    - jobs/test-soh-alive
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ appName }}
  namespace: {{ namespace }}
  labels:
    gms/type: {{ augmentationType }}
    gms/augmentation: {{ appName }}
    gms/user: {{ userName }}
spec:
  # If we fail, fail immediately
  backoffLimit: 0
  # TTL is Kubernetes v1.12 [alpha] feature
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccount: gms-soh-elevated
      restartPolicy: Never
      volumes:
        - name: shm
          emptyDir:
            sizeLimit: "2Gi"
            medium: "Memory"
      containers:
        - name: {{ appName }}
          image: {{ imageRegistry }}/{{ imageName }}:{{ imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 16
              memory: "8G"
            limits:
              cpu: 32
              memory: "16G"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          env:
            - name: GMS_TEST_NAME
              value: {{ appName }}
            - name: GMS_APP
              value: "soh"
            {%- if reporting | default(0) %}
            - name: MINIO_URL
              value: "http://minio:9000"
            - name: MINIO_REPORT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: "minio"
                  key:  minio_report_bucket
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "minio-keys"
                  key:  minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "minio-keys"
                  key:  minio_secret_key
            {% endif %}
            {%- for name in env %}
            - name: "{{ name }}"
              value: "{{ env[name] -}}"
            {% endfor %}
