{{- $appName := "frameworks-osd-service" }}
{{- $appValues := get .Values $appName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    restartAfterReconfig: {{ include "sb.deployment.restartAfterReconfig" (dict "Values" .Values "appValues" $appValues) }}
spec:
  replicas: {{ $appValues.replicas }}
  strategy:
    type: {{ include "sb.deployment.strategy" (dict "Values" .Values "appValues" $appValues) }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: gms-sb-elevated
      containers:
        - name: {{ $appName }}
          image: {{ include "sb.container.image" (dict "Values" .Values "appValues" $appValues) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: ETCD_GMS_USER
              valueFrom:
                secretKeyRef:
                  name: "etcd-gms-user"
                  key:  username
            - name: ETCD_GMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "etcd-gms-user"
                  key: password
            - name: GMS_CONFIG_SQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "postgres-soh-application"
                  key: username
            - name: GMS_CONFIG_SQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: "postgres-soh-application"
                  key: password
            {{- include "sb.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) }}
          ports:
            - containerPort: 8080
            - containerPort: 8383
          {{- include "sb.container.resources" (dict "Values" .Values "appValues" $appValues) | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
  selector:
    app: {{ $appName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}
spec:
  tls:
    - secretName: ingress-default-cert
      hosts:
        - "{{ .Release.Name }}.{{ .Values.baseDomain }}"
  rules:
    - host: "{{ .Release.Name }}.{{ .Values.baseDomain }}"
      http:
        paths:
          - path: "/{{ $appName }}"
            pathType: Prefix
            backend:
              service:
                name: {{ $appName }}
                port:
                  number: 8080
