---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  gms-sb-psp-role
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
    - use
- apiGroups:
    - ""
  resources:
    - pods
    - endpoints
  verbs:
    - get
    - list
    - watch
