parserOptions:
  project: './tsconfig.json'
extends:
  - '../../.eslintrc.yaml'
settings:
  import/resolver:
    # webpack:
    #   config: 'webpack.config.ts'
    node:
      extensions: ['.ts', '.tsx', '.js']
      moduleDirectory:
        - './node_modules'
        - '../../node_modules'
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
