{{- $appName := "postgresql-exporter" }}
{{- $appValues := get .Values $appName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    restartAfterReconfig: {{ include "ian.deployment.restartAfterReconfig" (dict "Values" .Values "appValues" $appValues) }}
spec:
  replicas: {{ $appValues.replicas }}
  strategy:
    type: {{ include "ian.deployment.strategy" (dict "Values" .Values "appValues" $appValues) }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: gms-ian-elevated
      containers:
        - name: {{ $appName }}
          image: {{ include "ian.container.image" (dict "Values" .Values "appValues" $appValues) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: "postgres-super-user"
                  key:  username
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: "postgres-super-user"
                  key:  password
            {{- include "ian.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) }}
          ports:
            - containerPort: 9187
          {{- include "ian.container.resources" (dict "Values" .Values "appValues" $appValues) | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9187
      protocol: TCP
      targetPort: 9187
  selector:
    app: {{ $appName }}
