{{- $appName := "reactive-interaction-gateway" }}
{{- $appValues := get .Values $appName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: ingress-default-cert
      hosts:
        - "{{ .Release.Name }}.{{ .Values.baseDomain }}"
  rules:
    - host: "{{ .Release.Name }}.{{ .Values.baseDomain }}"
      http:
        paths:
          - path: /{{ $appName }}/api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: "{{ $appName }}"
                port:
                  number: 4010
          - path: /{{ $appName }}/rig(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: "{{ $appName }}"
                port:
                  number: 4000
