---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gms-ian-psp-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gms-ian-psp-role
subjects:
- kind: ServiceAccount
  name: gms-ian-elevated
