export const processingConfiguration = {
  defaultNetwork: 'demo',
  defaultInteractiveAnalysisStationGroup: 'ALL_1',
  currentIntervalEndTime: 1274399999,
  currentIntervalDuration: 7200,
  waveformViewablePaddingDuration: 900,
  defaultFilters: [
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 0.7,
      filterSource: 'SYSTEM',
      sampleRate: 20,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 0.70-2.00 Hz',
      id: '48fd578e-e428-43ff-9f9e-62598e7e6ce6',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 2,
      description: 'Hamming FIR Filter Band Pass, 0.70-2.00 Hz',
      groupDelaySecs: 1.2
    },
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 0.7,
      filterSource: 'SYSTEM',
      sampleRate: 40,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 0.70-2.00 Hz',
      id: '0351d87a-fde9-43e2-8754-84a1d797fbc1',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 2,
      description: 'Hamming FIR Filter Band Pass, 0.70-2.00 Hz',
      groupDelaySecs: 0.6
    },
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 1,
      filterSource: 'SYSTEM',
      sampleRate: 20,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 1.00-3.00 Hz',
      id: '56893621-d9a1-4cfd-830a-13969f9d2aad',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 3,
      description: 'Hamming FIR Filter Band Pass, 1.00-3.00 Hz',
      groupDelaySecs: 1.2
    },
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 1,
      filterSource: 'SYSTEM',
      sampleRate: 40,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 1.00-3.00 Hz',
      id: '8bab76bd-db1a-4226-a151-786577adb3d8',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 3,
      description: 'Hamming FIR Filter Band Pass, 1.00-3.00 Hz',
      groupDelaySecs: 0.6
    },
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 4,
      filterSource: 'SYSTEM',
      sampleRate: 20,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 4.00-8.00 Hz',
      id: 'db5e61a0-b8dc-48a7-b56c-5e497925e89c',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 8,
      description: 'Hamming FIR Filter Band Pass, 4.00-8.00 Hz',
      groupDelaySecs: 1.19999999999
    },
    {
      filterCausality: 'CAUSAL',
      lowFrequencyHz: 4,
      filterSource: 'SYSTEM',
      sampleRate: 40,
      filterType: 'FIR_HAMMING',
      name: 'HAM FIR BP 4.00-8.00 Hz',
      id: 'b92d6ade-3e69-42b6-82e5-f9290f50120f',
      bCoefficients: [],
      order: 48,
      validForSampleRate: true,
      aCoefficients: [1],
      sampleRateTolerance: 0.05,
      zeroPhase: false,
      filterPassBandType: 'BAND_PASS',
      highFrequencyHz: 8,
      description: 'Hamming FIR Filter Band Pass, 4.00-8.00 Hz',
      groupDelaySecs: 0.6
    }
  ]
};
