---- MAIN CSS DDL

CREATE SCHEMA IF NOT EXISTS GNEM_GMS AUTHORIZATION GNEM_GMS;

-- TODO get this to work with reserved table name "INTERVAL"
CREATE TABLE IF NOT EXISTS GNEM_GMS.INTERVAL_TABLE
(
    CLASS VARCHAR2(16) not null,
    ENDTIME FLOAT(53) not null,
    NAME VARCHAR2(50) not null,
    TIME FLOAT(53) not null,
    AUTH VARCHAR2(15),
    COMMID NUMBER(18),
    INTVLID NUMBER(18),
    LDDATE DATE,
    MODDATE DATE,
    PERCENT_AVAILABLE FLOAT(53),
    PROC_END_DATE DATE,
    PROC_START_DATE DATE,
    STATE VARCHAR2(16),
    constraint INTERVAL_PK
        primary key (CLASS, ENDTIME, NAME, TIME)
);


---- SIMULATOR CSS DDL

CREATE SCHEMA IF NOT EXISTS GNEM_GMS_SIMULATION AUTHORIZATION GNEM_GMS;

-- TODO get this to work with reserved table name "INTERVAL"
CREATE TABLE IF NOT EXISTS GNEM_GMS_SIMULATION.INTERVAL_TABLE
(
    CLASS VARCHAR2(16) not null,
    ENDTIME FLOAT(53) not null,
    NAME VARCHAR2(50) not null,
    TIME FLOAT(53) not null,
    AUTH VARCHAR2(15),
    COMMID NUMBER(18),
    INTVLID NUMBER(18),
    LDDATE DATE,
    MODDATE DATE,
    PERCENT_AVAILABLE FLOAT(53),
    PROC_END_DATE DATE,
    PROC_START_DATE DATE,
    STATE VARCHAR2(16),
    constraint INTERVAL_PK
        primary key (CLASS, ENDTIME, NAME, TIME)
);
